services:
    app-node:
        build:
            context: .
            dockerfile: src/Dockerfile
            args:
                ARCHITECTURE: ${ARCHITECTURE}
                NODE_VERSION: ${NODE_VERSION}
        deploy:
            replicas: ${REPLICAS}
    nginx-server:
        depends_on:
            -   app-node
        build:
            context: .
            args:
                ARCHITECTURE: ${ARCHITECTURE}
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            -  "${PORT}:80"
