apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.org/rewrites: "serviceName=runcontrol-server-service rewrite=/"
spec:
  ingressClassName: nginx
  rules:
    - host: bril-cluster # IP is not accepted
      http:
        paths: # first matching path will be applied
          - path: /webmonitor18
            pathType: Prefix
            backend:
              service:
                name: webmonitor-service
                port:
                  number: 3000
          - path: /runcontrol18/api/
            pathType: Prefix
            backend:
              service:
                name: runcontrol-server-service
                port:
                  number: 5010
          - path: /runcontrol18
            pathType: Prefix
            backend:
              service:
                name: runcontrol-client-service
                port:
                  number: 3000
