apiVersion: v1
kind: Secret
metadata:
  name: oracle-db.config
type: Opaque
stringData:
  db.ini: |
    [<name>]
    protocol=<protocol>
    user=<user>
    pwd=<base64_password>
    descriptor=<descriptor>
    service=<service>
