apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-logs
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    server: <master_ip> # IP address of your NFS service
    path: "/mnt/shared"